### ISSUE TITLE
VOQC got stuck when optimizing circuits

### ISSUE THREAD

**Issue by tnguyen-ornl** [inQWIRE/SQIR#7] opened 2020-08-09 13:33 UTC
When using VOQC to optimize quantum circuits, there are several cases where VOQC got stuck (not complete after > 1 hour).

One such example is this qasm file https://github.com/CQCL/tket_benchmarking/blob/master/active/qasm_files/square_root_7.qasm

Thanks!

**Comment by khieta** [comment] 2020-08-09 14:41
Thanks for reporting this. The issue is an inefficiency in our not_propagation routine (see Sec 4.3 of our [draft](https://arxiv.org/pdf/1912.02250.pdf)). We hadn't observed this behavior yet because the benchmarks we considered use few, if any, X gates.

I'll start working on this now. I should be able to push a solution within a few days.

**Comment by tnguyen-ornl** [comment] 2020-08-10 13:52
Thank you for your quick response. I'm looking forward to checking out the fixed version.

**Comment by khieta** [comment] 2020-08-10 20:13
I pushed the fix. Here's the output of running VOQC on the square root example on my machine:
```
$ cd VOQC
$ dune exec -- ./voqc.exe -i path/to/square_root_7.qasm -o out.qasm
Input file: path/to/square_root_7.qasm
Output file: out.qasm
Time to parse: 0.349963s
Original:	 Total 7630, Rz 3336, Clifford 417, T 2919, H 985, X 220, CNOT 3089
Time to optimize: 0.233084s
Final:	 Total 5122, Rz 1591, Clifford 468, T 1123, H 573, X 7, CNOT 2951
Time to write out: 0.002574s
```
Let us know if you spot any other issues!

**Closed by khieta** 2020-08-10 20:13 UTC
